<a href="https://colab.research.google.com/github/jacobhallburns/CSE_2010_Algorithms_and_Data_Structures_Term_Project_2024/blob/main/robotArmFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
""" Kinematic chain of a robot arm (planar)
    Assignment
"""

' Kinematic chain of a robot arm (planar)\n    Assignment\n'


![](https://github.com/eraldoribeiro/assignment_robotarm2D/blob/main/robotArm01.png?raw=1)
*Figure 1*: A two-dimensional articulated arm. The articulated structure has 3 local coordinate frames each one centered at a joint. For each part, the local x-axis is aligned with the part.  

Consider the arm structure shown in Figure 1. Assume the following values for the arm configuration:
- The location of the first joint (i.e., the one that is attached to the ground support) is ${\bf p}_1 = \left(3,2\right)^\mathsf{T}$.
- The lengths of the parts are $L_1 = 5$ and  $L_2 = 8$.

In [40]:
import numpy as np
import math as mph

### Question 1

Write the matrices that represent the local coordinate frames $\mathcal F\{1\}$, $\mathcal F\{2\}$, and $\mathcal F\{3\}$. These frames are indicated in green in Figure 1. The transformation matrices you need to write are $T_{0,1}$, $T_{1,2}$, and $T_{2,3}$.

In [41]:
# Answer goes here. Add more code/markdown cells as needed
phi_0 = 0
phi_1 = np.pi / 8
phi_2 = np.pi / 4
L1 = 5
L2 = 8

T01 = np.array([[np.cos(phi_0), -np.sin(phi_0), 3],
                [np.sin(phi_0),  np.cos(phi_0), 2],
                [            0,              0, 1]
               ])
T12 = np.array([[np.cos(phi_1), -np.sin(phi_1), L1],
                [np.sin(phi_1),  np.cos(phi_1),  0],
                [            0,              0,  1]
               ])

T23 = np.array([[np.cos(phi_2), -np.sin(phi_2), L2],
                [np.sin(phi_2),  np.cos(phi_2),  0],
                [            0,              0,  1]
               ])
print(f"\nT01 = \n{T01}")
print(f"\nT12 = \n{T12}")
print(f"\nT23 = \n{T23}")


T01 = 
[[ 1. -0.  3.]
 [ 0.  1.  2.]
 [ 0.  0.  1.]]

T12 = 
[[ 0.92387953 -0.38268343  5.        ]
 [ 0.38268343  0.92387953  0.        ]
 [ 0.          0.          1.        ]]

T23 = 
[[ 0.70710678 -0.70710678  8.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [42]:
# Point written w.r.t. Frame 1
p = np.array([[0],[0],[1]])

In [43]:
# Point Written w.r.t. Frame 0 (global frame)
p_0 = T01 @ p
p_1 = T12 @ p
p_2 = T23 @ p
print(f"\nPoint 1 = \n{p_0}")
print(f"\nPoint 2 = \n{p_1}")
print(f"\nPoint 3 = \n{p_2}")


Point 1 = 
[[3.]
 [2.]
 [1.]]

Point 2 = 
[[5.]
 [0.]
 [1.]]

Point 3 = 
[[8.]
 [0.]
 [1.]]


### Question 2

Write the matrices that represent each local frame w.r.t. the global frame $\mathcal F\{0\}$. The transformations you need to write are $T_{0,1}$, $T_{0,2}$, and $T_{0,3}$.

In [44]:
# Answer goes here. Add more code/markdown cells as needed




### Question 3

Write the matrices that represent the local coordinate frames $\mathcal F\{1\}$, $\mathcal F\{2\}$, and $\mathcal F\{3\}$. These frames are indicated in green in Figure 1. The transformation matrices you need to write are $T_{0,1}$, $T_{1,2}$, and $T_{2,3}$.

In [45]:
# Answer goes here. Add more code/markdown cells as needed




### Question 4

Using the transformations from the previous questions, calculate the global coordinates of the middle point of each part of the robot arm when $\phi_1 = \pi/8$ and $\phi_2 = \pi/4$. Hint: the location of the middle point of part 1 is $(\frac{L_1}{2},0)^\mathsf{T}$ (w.r.t. frame $\mathcal F\{1\}$).

In [46]:
# Answer goes here. Add more code/markdown cells as needed






### Question 5

Using the transformations from the previous questions, calculate the global coordinates of all the joint points and the end-effector location when $\phi_1 = \pi/4$ and $\phi_2 = \pi/8$.

In [47]:
# Answer goes here. Add more code/markdown cells as needed





### Question 6

Write the matrix that represents the coordinate frame of the end effector w.r.t. frame  $\mathcal F\{1\}$, i.e., $T_{1,3}$

In [48]:
# Answer goes here. Add more code/markdown cells as needed




### Question 7

Write the matrix that represents the coordinate frame $\mathcal F\{1\}$ w.r.t. to the frame of the end effector

In [49]:
# Answer goes here. Add more code/markdown cells as needed


